### ISSUE TITLE
Structure the github archive payload field on BigQuery

### ISSUE THREAD

**Issue by kozikow** [igrigorik/githubarchive.org#148]
github archive tables on BigQuery, like https://bigquery.cloud.google.com/table/githubarchive:month.201607 contain very relevant info in payload field.

Currently, the only option to extract information from this field using BigQuery is to use functions like JSON_EXTRACT_SCALAR. Due to pricing of BigQuery it's expensive, as queries pay for accessing the whole payload field.

Another BigQuery table, https://bigquery.cloud.google.com/table/bigquery-public-data:samples.github_nested, contains parsed payload field, accessible in columnar format. Sadly, this table is only a small sample.

Structured payload field in github archive tables would make it much cheaper and easier to query this table.

**Comment by igrigorik** [comment]
(Unfortunately) this is a conscious tradeoff. As you outlined, a fully structured schema allows more efficient analysis, but unfortunately it is also very brittle and impossible to maintain over the long-term, which is why we switched to a combination of a few static fields + JSON fields. You can read more about this here: https://github.com/igrigorik/githubarchive.org/issues/112#issuecomment-222857267

Closing, as this a "won't fix".

Thanks for your feedback!
