### ISSUE TITLE
Username being populated on 3rd party site

### ISSUE THREAD

**Issue by D3m0nKingx** [igrigorik/githubarchive.org#158]
https://opensourcecontributo.rs/archive/events/2016-04-15-12.users.txt

discovered my github username on this generated txt file. I emailed the admin of the site, liam@tenex.tech

He informed me it is populated directly from githubarchive.org. which I found through a google search of my email address. Could this possibly be prevented? As my concern is my email address being publicly posted without my consent. Or some option put in place that allows users to control the publicity of their account info across non-github sites?

**Comment by hut8** [comment]
Hey. To clarify: your email address isn't in that text file, right? I'm probably going to delete all of the index files (.users.txt) in the near future. Would that resolve the issue? It's just the one text file that matters?

**Comment by D3m0nKingx** [comment]
Correct, email address wasn't contained in the txt file. It was that it came up in a google search.. So yes that should resolve it.

**Comment by igrigorik** [comment]
By the sounds of it, nothing actionable for GH Archive here.. closing. Feel free to reopen if otherwise. Also, note that we're hashing emails as of earlier in the year: https://github.com/igrigorik/githubarchive.org/commit/7567623bdb9ebfc73f9778dc8372e0dace79ea2f#diff-069840a758b518e30c7fab9398b2b23dR186
