### ISSUE TITLE
many repo ids are null, 2012-03 to 2012-09

### ISSUE THREAD

**Issue by fhoffa** [igrigorik/githubarchive.org#161]
Many ids are 'null', starting on March 2012 until September 2012.

I noticed by the gap on charting this:

![image](https://cloud.githubusercontent.com/assets/4095866/23210891/4f867006-f8b4-11e6-9f4b-c905e7de9805.png)

On a closer look, May 2012 shows that the repo and actor names are filled in, but not their ids:

![image](https://cloud.githubusercontent.com/assets/4095866/23210951/903018aa-f8b4-11e6-9973-b5cedd6ce259.png)

https://bigquery.cloud.google.com/table/githubarchive:month.201205?tab=preview

**Comment by igrigorik** [comment]
Unfortunately it looks like the problem is in the data that GitHub was providing via their API.. I've poked around a few (raw) archives and `id` was missing for that period of time. Here's a quick comparison between May vs November of 2012: https://gist.github.com/igrigorik/644e03152771a2528de78d4f2b9c89e9 - no id for repositories.

Can you use `name` for what you're trying to do?

**Comment by fhoffa** [comment]
The problem with "name" is that many repos change name through their history. In fact, none of the names there is a name today (they all have a / now). But not much to do here apparently..

**Comment by igrigorik** [comment]
Right, unfortunately that's not something we can fix on this end..
