### ISSUE TITLE
githubarchive is missing issue assignee and label events resulting in inaccurate issue analysis

### ISSUE THREAD

**Issue by helenalt** [igrigorik/githubarchive.org#173]
I am using githubarchive to analyze team's responsiveness to issues and PRs, and noticed that some events are missing in githubarchive, resulting in issue assignee and labels not being reflected. 
Example:
select *
from  TABLE_DATE_RANGE([githubarchive:day.],TIMESTAMP('2017-12-01'),TIMESTAMP('2018-01-18'))
WHERE
  repo.name="bazelbuild/bazel"
  and JSON_EXTRACT(payload, '$.issue.number')="4316"

Results in 1 row without assignee and label while in github it was assigned to laurentlb and classified with label: "category: extensibility > skylark" on Dec 18, 2017
Over 700 of my issues fit into this category, preventing from doing accurate analysis. Same issue is for PRs although labels are less of a concern for me there.

Appreciate insight into whether there is another way to do this or when all events will be captured in githubarchive so that it represents a complete snapshot for each issue.

**Comment by igrigorik** [comment]
> Over 700 of my issues fit into this category, preventing from doing accurate analysis. Same issue is for PRs although labels are less of a concern for me there.

Yikes. What fraction of total does this represent? Hard to say for certain, but this may be due to https://github.com/igrigorik/githubarchive.org/issues/171.

**Comment by helenalt** [comment]
About 40%, I definitely need this data before I can use githubarchive for
our user community reporting. Is it possible to do a one-time scrub to get
those missed events, and maybe repeat it monthly until the issue is
addressed?

**Comment by annafil** [comment]
👋 @helenalt I dug around the API source that Archive is polling to get events data -- I think that the reason the label and issue assignee events are not available in Archive is because they aren't being sent by the original API source from GitHub. 

There is another way you can get at this information. Every 'IssuesEvent' record contains an API link to the events associated with this issue. You can follow those links to get at additional events, like assigning an issue or creating a label. 

In the case of your example, this would be the URL you can follow and you'll find the events you're looking for here: https://api.github.com/repos/bazelbuild/bazel/issues/4316/events

Note that because this is pointing directly to the GitHub API you might run into a rate limit pretty quickly by just browsing the links. If you authenticate with a GitHub account, you will be able to get more data. More about authentication and rate limits here: https://developer.github.com/v3/#authentication

**Comment by igrigorik** [comment]
@annafil thanks a lot for digging into this.
@helenalt as Anna noted, the missing data is not provided by the events API, so there is not much we can do about it on this end. Closing, feel free to reopen if there is more to explore here.
